"use client"

import { OctagonAlert } from "lucide-react"
import React, { FC, useState } from "react"

import { Markdown } from "@/components/markdown/markdown"
import Typography from "@/components/typography"
import { calculateFleschKincaidScore } from "@/features/chat/chat-services/chat-flesch"
import { CreateUserFeedback } from "@/features/chat/chat-services/chat-message-service"
import { useChatContext } from "@/features/chat/chat-ui/chat-context"
import { ChatRole, ChatSentiment, FeedbackType, PromptMessage } from "@/features/chat/models"
import { showError } from "@/features/globals/global-message-store"
import { AI_NAME } from "@/features/theme/theme-config"
import { AssistantButtons, FleschButton } from "@/features/ui/assistant-buttons"
import Modal from "@/features/ui/modal"

interface ChatRowProps {
  chatMessageId: string
  name: string
  message: PromptMessage
  type: ChatRole
  chatThreadId: string
  showAssistantButtons: boolean
  threadLocked?: boolean
}

export const ChatRow: FC<ChatRowProps> = props => {
  const [isIconChecked, setIsIconChecked] = useState(false)
  const [thumbsUpClicked, setThumbsUpClicked] = useState(props.message.sentiment === ChatSentiment.Positive)
  const [thumbsDownClicked, setThumbsDownClicked] = useState(props.message.sentiment === ChatSentiment.Negative)

  const [feedbackType, setFeedbackType] = useState(props.message.feedback)
  const [feedbackReason, setFeedbackReason] = useState(props.message.reason)

  const [feedbackMessage, setFeedbackMessage] = useState("")
  const [isFeedbackModalOpen, setFeedbackModalOpen] = useState(false)
  const { openModal, closeModal } = useChatContext()

  const toggleButton = (buttonId: string): void => {
    switch (buttonId) {
      case "ThumbsUp":
        setThumbsUpClicked(prevState => !prevState)
        setThumbsDownClicked(false)
        setIsIconChecked(false)
        CreateUserFeedback(
          props.chatMessageId,
          FeedbackType.None,
          ChatSentiment.Positive,
          "",
          props.chatThreadId
        ).catch(err => showError(err))
        break
      case "ThumbsDown":
        setThumbsDownClicked(prevState => !prevState)
        setThumbsUpClicked(false)
        setIsIconChecked(false)
        break
      case "CopyButton":
        setIsIconChecked(prevState => !prevState)
        setThumbsUpClicked(false)
        setThumbsDownClicked(false)
        break
      default:
        break
    }
  }

  const handleCopyButton = (): void => {
    toggleButton("CopyButton")
    const messageWithAttribution = props.message.content + ("\n\nText generated by " + AI_NAME)
    navigator.clipboard
      .writeText(messageWithAttribution)
      .then(() => {
        setFeedbackMessage("Message copied to clipboard.")
      })
      .catch(_err => {
        setFeedbackMessage("Something happened and the message has not been copied.")
      })
      .finally(() => setTimeout(() => setFeedbackMessage(""), 2000))
  }

  const handleThumbsUpClick = (): void => {
    toggleButton("ThumbsUp")
    setFeedbackMessage("Positive feedback submitted.")
    setTimeout(() => setFeedbackMessage(""), 2000)

    setFeedbackType(FeedbackType.None)
    setFeedbackReason("")
  }

  const handleThumbsDownClick = (): void => {
    setFeedbackModalOpen(true)
    openModal?.()
  }

  async function handleModalSubmit(): Promise<void> {
    const resp = await CreateUserFeedback(
      props.chatMessageId,
      feedbackType || FeedbackType.None,
      ChatSentiment.Negative,
      (feedbackReason || "").trim(),
      props.chatThreadId
    )

    if (resp.status !== "OK") {
      showError("Failed to submit feedback.")
      return
    }

    if (!thumbsDownClicked) toggleButton("ThumbsDown")

    setFeedbackMessage("Negative feedback submitted.")
    setTimeout(() => setFeedbackMessage(""), 2000)

    setFeedbackModalOpen(false)
    closeModal?.()
  }

  const handleModalClose = (): void => {
    setFeedbackModalOpen(false)
    closeModal?.()
  }

  const fleshScore = calculateFleschKincaidScore(props.message.content)

  const safetyWarning = props.message.contentFilterResult ? (
    <div
      className="my-2 flex max-w-none justify-center space-x-2 rounded-md bg-alert p-2 text-base text-primary md:text-base"
      tabIndex={0}
      aria-label="Content Safety Warning"
    >
      <div className="flex items-center justify-center">
        <OctagonAlert size={20} />
      </div>
      <div className="flex flex-grow items-center justify-center text-center">
        <Typography variant="p" className="m-0">
          This message has triggered one of our content safety warnings, please rephrase your message, start a new chat,
          or reach out to{" "}
          <a href="/support" className="text-primary underline" aria-label="Go to support page">
            support
          </a>{" "}
          if you have concerns.
        </Typography>
      </div>
      <div className="flex items-center justify-center">
        <OctagonAlert size={20} />
      </div>
    </div>
  ) : null

  return (
    <article className={"container mx-auto flex flex-col py-1 pb-2"}>
      <section
        className={`prose prose-slate max-w-none flex-col gap-4 overflow-hidden break-words rounded-md px-4 py-2 text-base text-text dark:prose-invert prose-p:leading-relaxed prose-pre:p-0 md:text-base ${props.threadLocked && "border-4 border-error"} ${props.type === "assistant" && "bg-backgroundShade"} ${props.type != "assistant" && "bg-altBackgroundShade"}`}
      >
        <div className="flex w-full items-center justify-between">
          {props.type === "assistant" && (
            <Typography variant="h3" className="m-0 flex-1 text-heading" tabIndex={0}>
              {props.name}
            </Typography>
          )}
          <div className="flex items-center gap-4">
            {props.type === "assistant" && props.showAssistantButtons && (
              <AssistantButtons
                isIconChecked={isIconChecked}
                thumbsUpClicked={thumbsUpClicked}
                thumbsDownClicked={thumbsDownClicked}
                handleCopyButton={handleCopyButton}
                handleThumbsUpClick={handleThumbsUpClick}
                handleThumbsDownClick={handleThumbsDownClick}
              />
            )}
            {props.type === "assistant" && props.showAssistantButtons && <FleschButton fleschScore={fleshScore} />}
          </div>
          <Modal
            chatThreadId={props.chatThreadId}
            chatMessageId={props.chatMessageId}
            feedbackType={feedbackType}
            onFeedbackTypeChange={setFeedbackType}
            feedbackReason={feedbackReason}
            onFeedbackReasonChange={setFeedbackReason}
            open={isFeedbackModalOpen}
            onClose={handleModalClose}
            onSubmit={handleModalSubmit}
          />
        </div>
        <div
          className="prose prose-slate max-w-none break-words text-base text-text dark:prose-invert prose-p:leading-relaxed prose-pre:p-0 md:text-base"
          tabIndex={0}
        >
          {props.type === "assistant" && <Markdown content={props.message.content} />}
          {props.type != "assistant" && <Markdown content={"**" + props.name + "**" + ": " + props.message.content} />}
        </div>
        {safetyWarning}
        <div className="sr-only" aria-live="assertive">
          {feedbackMessage}
        </div>
      </section>
    </article>
  )
}
export default ChatRow
