import { Message } from "ai"
import { Menu, File, Clipboard, Bird } from "lucide-react"
import { getSession } from "next-auth/react"
import React, { useEffect, useRef, useCallback } from "react"

import { APP_NAME } from "@/app-global"

import { useChatContext } from "@/features/chat/chat-ui/chat-context"
import { useGlobalMessageContext } from "@/features/globals/global-message-context"
import { Button } from "@/features/ui/button"
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/features/ui/dropdown-menu"

interface ChatInputMenuProps {
  onDocExport: () => void
  messageCopy: Message[]
}
const ChatInputMenu: React.FC<ChatInputMenuProps> = ({ onDocExport }) => {
  const { setInput, handleSubmit, messages } = useChatContext()
  const firstMenuItemRef = useRef<HTMLDivElement>(null)
  const { showError, showSuccess } = useGlobalMessageContext()
  useEffect(() => {
    if (firstMenuItemRef.current) {
      firstMenuItemRef.current.focus()
    }
  }, [])

  const fairClickHandler = useCallback((): void => {
    const fairInput = "Help me complete a Queensland Government Foundational AI Risk Assessment (FAIRA)"
    setInput(fairInput)
    setTimeout(() => {
      handleSubmit({ preventDefault: () => {} } as React.FormEvent<HTMLFormElement>)
    }, 0)
  }, [setInput, handleSubmit])

  const copyToClipboard = useCallback(async (): Promise<void> => {
    try {
      const session = await getSession()
      const name = session?.user?.name || "You"
      const formattedMessages = messages
        .map(message => {
          const author = message.role === "system" || message.role === "assistant" ? APP_NAME : name
          return `${author}: ${message.content}`
        })
        .join("\n")
      const formattedMessagesWithAttribution = `${formattedMessages}\n\nChat generated by ${APP_NAME}`
      await navigator.clipboard.writeText(formattedMessagesWithAttribution)
      showSuccess({ title: "Copied", description: "Conversation copied to clipboard" })
    } catch (_error) {
      showError("Failed to copy messages to clipboard. Click to download the chat document.", onDocExport)
    }
  }, [messages, showError, showSuccess, onDocExport])

  return (
    <DropdownMenu>
      <DropdownMenuTrigger>
        <Button
          aria-haspopup="true"
          aria-expanded="false"
          aria-controls="chat-input-options"
          ariaLabel="Open chat input options menu"
          type="button"
          variant="ghost"
          size="icon"
        >
          <Menu aria-hidden="true" focusable="false" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        id="chat-input-options"
        role="menu"
        aria-label="Chat input options"
        className="z-90 min-w-[220px] rounded-md bg-background p-[5px] text-popover-foreground shadow-lg"
        sideOffset={5}
      >
        <DropdownMenuItem
          onSelect={fairClickHandler}
          className="DropdownMenuItem cursor-pointer rounded-md bg-background text-foreground hover:bg-secondary hover:text-secondary-foreground"
        >
          <div tabIndex={0} ref={firstMenuItemRef} className="flex items-center p-2">
            <Bird size={20} className="mr-2" aria-hidden="true" />
            Complete a Foundational AI Risk Assessment
          </div>
        </DropdownMenuItem>
        <DropdownMenuSeparator className="my-2 h-px bg-secondary" />
        <DropdownMenuItem
          onSelect={onDocExport}
          className="flex cursor-pointer items-center rounded-md p-2 hover:bg-secondary hover:text-secondary-foreground"
        >
          <File size={20} className="mr-2" aria-hidden="true" />
          Export your Chat to File
        </DropdownMenuItem>
        <DropdownMenuSeparator className="my-2 h-px bg-secondary" />
        <DropdownMenuItem
          onSelect={copyToClipboard}
          className="flex cursor-pointer items-center rounded-md p-2 hover:bg-secondary hover:text-secondary-foreground"
        >
          <Clipboard size={20} className="mr-2" aria-hidden="true" />
          Copy Chat to Clipboard
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default ChatInputMenu
