"use client";
import { AddExtension } from "@/features/extensions-page/add-extension/add-new-extension";
import { ExtensionCard } from "@/features/extensions-page/extension-card/extension-card";
import { ExtensionModel } from "@/features/extensions-page/extension-services/models";
import { ChatInput } from "@/features/chat-page/chat-input/chat-input";
import { chatStore, useChat } from "@/features/chat-page/chat-store";
import { PersonaCard } from "@/features/persona-page/persona-card/persona-card";
import { PersonaModel } from "@/features/persona-page/persona-services/models";
import { ChatHomeHeader } from "./chat-home-header/chat-home-header";
import { ScrollArea } from "@/features/ui/scroll-area";
import { ChatLoading } from "@/features/ui/chat/chat-message-area/chat-loading";
import Disclaimer from "@/features/ui/chat/disclaimer";
import { FC, useEffect } from "react";
import { NEW_CHAT_NAME } from "@/features/theme/theme-config";

interface ChatPersonaProps {
  personas: PersonaModel[];
  extensions: ExtensionModel[];
}

export const ChatHome: FC<ChatPersonaProps> = (props) => {
  const { loading } = useChat();
  
  // Reset chat store when component mounts
  useEffect(() => {
    // Reset the chat store to ensure a fresh state
    chatStore.initChatSession({
      chatThread: {
        id: "", // Empty ID will trigger new thread creation
        name: NEW_CHAT_NAME,
        createdAt: new Date(),
        lastMessageAt: new Date(),
        userId: "",
        useName: "",
        isDeleted: false,
        bookmarked: false,
        personaMessage: "",
        personaMessageTitle: "",
        extension: [],
        type: "CHAT_THREAD",
      },
      messages: [],
      userName: chatStore.userName || "",
    });
  }, []);
  return (
    <main className="flex flex-1 relative flex-col h-screen overflow-hidden">
      <ChatHomeHeader />
      {/* Loading overlay shown when submitting a chat */}
      <div 
        className={`absolute inset-0 bg-background z-50 flex items-center justify-center transition-opacity duration-300 ${
          loading === "loading" ? "opacity-100" : "opacity-0 pointer-events-none"
        }`}
      >
      </div>
      <ScrollArea className="flex-1" style={{ height: 'calc(100vh - 190px)' }}>
        <div className="flex flex-1 flex-col gap-6 pb-6 pt-6">
        <div className="container max-w-4xl flex gap-20 flex-col">
          <div>
            <h2 className="text-2xl font-bold mb-3">Extensions</h2>

            {props.extensions && props.extensions.length > 0 ? (
              <div className="grid grid-cols-3 gap-3">
                {props.extensions.map((extension) => {
                  return (
                    <ExtensionCard
                      extension={extension}
                      key={extension.id}
                      showContextMenu={false}
                    />
                  );
                })}
              </div>
            ) :
              <p className="text-muted-foreground max-w-xl">No extentions created</p>
            }

          </div>
          <div>
            <h2 className="text-2xl font-bold mb-3">Personas</h2>

            {props.personas && props.personas.length > 0 ? (
              <div className="grid grid-cols-3 gap-3">
                {props.personas.map((persona) => {
                  return (
                    <PersonaCard
                      persona={persona}
                      key={persona.id}
                      showContextMenu={false}
                    />
                  );
                })}
              </div>
            ) :
              <p className="text-muted-foreground max-w-xl">No personas created</p>
            }
          </div>
          </div>
          <AddExtension />
        </div>
      </ScrollArea>
      
      {/* Footer with chat input below Line 2 */}
      <div className="py-4 bg-white dark:bg-slate-950">
        <div className="flex flex-col items-center px-4 max-w-4xl mx-auto w-full">
          <div className="w-full backdrop-blur rounded-xl ">
            <ChatInput />
          </div>
          <div className="text-center text-sm text-muted-foreground mt-1">
            <Disclaimer text={"The information generated by COMAU AICO could be wrong, please verify before using it."} />
          </div>
        </div>
      </div>
    </main>
  );
};
