FROM node:alpine AS base

RUN apk --no-cache upgrade && \
  apk add --no-cache ca-certificates libc6-compat \
  && mkdir -p /etc/pki/ca-trust/source/anchors \
  && update-ca-certificates

WORKDIR /app

FROM base AS deps

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG APPLICATION_INSIGHTS
ARG BUILD_ID
ARG FEATURE_TRANSCRIBE_TENANTS
ARG FEATURE_TRANSLATOR
ARG PUBLIC_API_URL

ENV AZURE_BUILD_ID=$BUILD_ID
ENV NEXT_PUBLIC_API_URL=$PUBLIC_API_URL
ENV NEXT_PUBLIC_APPLICATIONINSIGHTS_CONNECTION_STRING=$APPLICATION_INSIGHTS
ENV NEXT_PUBLIC_FEATURE_TRANSLATOR=$FEATURE_TRANSLATOR
ENV NEXT_PUBLIC_FEATURE_TRANSCRIBE_TENANTS=$FEATURE_TRANSCRIBE_TENANTS

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs && \
  adduser --system --uid 1001 nextjs

# Copy the build output and static files from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY package.json package-lock.json* ./

USER nextjs

ENV PORT 443
ENV HOSTNAME 0.0.0.0

CMD ["node", "server.js"]
