declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ADMIN_EMAIL_ADDRESS: string
      ANALYZE: string
      AZURE_AD_AUTHORIZATION_ENDPOINT: string
      AZURE_AD_CLIENT_ID: string
      AZURE_AD_CLIENT_SECRET: string
      AZURE_AD_OPENID_CONFIGURATION: string
      AZURE_AD_REDIRECT_URL: string
      AZURE_AD_TENANT_ID: string
      AZURE_AD_TOKEN_ENDPOINT: string
      AZURE_AD_USERINFO_ENDPOINT: string
      AZURE_COSMOSDB_CONFIG_CONTAINER_NAME: string
      AZURE_COSMOSDB_CONTAINER_NAME: string
      AZURE_COSMOSDB_DB_NAME: string
      AZURE_COSMOSDB_KEY: string
      AZURE_COSMOSDB_TENANT_CONTAINER_NAME: string
      AZURE_COSMOSDB_URI: string
      AZURE_COSMOSDB_USER_CONTAINER_NAME: string
      AZURE_COSMOSDB_USER_PREFS_CONTAINER_NAME: string
      AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: string
      AZURE_DOCUMENT_INTELLIGENCE_KEY: string
      AZURE_KEY_VAULT_NAME: string
      AZURE_OPENAI_API_DEPLOYMENT_NAME: string
      AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME: string
      AZURE_OPENAI_API_INSTANCE_NAME: string
      AZURE_OPENAI_API_KEY: string
      AZURE_OPENAI_API_VERSION: string
      AZURE_SEARCH_API_KEY: string
      AZURE_SEARCH_API_VERSION: string
      AZURE_SEARCH_INDEX_NAME: string
      AZURE_SEARCH_NAME: string
      AZURE_SPEECH_KEY: string
      AZURE_SPEECH_REGION: string
      AZURE_SPEECH_STT_URL: string
      AZURE_SPEECH_URL: string
      AZURE_TRANSLATOR_KEY: string
      AZURE_TRANSLATOR_URL: string
      FEATURE_FILEEXPORT: string
      FEATURE_QUASYMODO: string
      NEXT_PUBLIC_FEATURE_TRANSCRIBE_TENANTS: string
      MAX_DOCUMENT_SIZE: string
      NEXT_PUBLIC_API_URL: string
      NEXT_PUBLIC_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING: string
      NEXT_PUBLIC_FEATURE_TRANSLATOR: string
      NEXTAUTH_SECRET: string
      NEXTAUTH_URL: string
      PROMPT_BUTTON_ENABLED: string
      PUBLIC_SPEECH_ENABLED: string
      QGAIP_APIM_BASE: string
      QGAIP_APIM_HEALTHCHECK_URI: string
      QGAIP_QCHAT_APP_URI: string
      QGAIP_QCHAT_FQDN_URI: string
      SYSTEM_PROMPT: string
    }
  }
}
export {}
