export { Administrators } from "./administrators"
export { DepartmentName } from "./department-name"
export { DomainDetails } from "./domain-details"
export { GroupList } from "./group-list"
export { LoginManagement } from "./login-management"
export { TenantDetailsForm } from "./tenant-details-form"
export { SupportEmail } from "./support-email"
